### ISSUE TITLE
Use shiftwidth instead of tabstop for indent guides

### ISSUE THREAD

**Issue by p00f** [akiyosi/goneovim#201]
I think goneovim uses `tabstop` for indent guides, can `shiftwidth` be used instead? (I keep `tabstop` to the standard 8 and use `softtabstop` 4, `shiftwidth` 4)

**Comment by akiyosi** [comment]
Hi,
Thanks for this issue report.
Yes, by default, goneovim uses `tabstop` value for drawing indented guides.
Regarding your request, I have made it possible to specify in the configuration the option to use for the guide width criteria.

https://github.com/akiyosi/goneovim/actions/runs/642873973

You can set shiftwidth as the base width of the indentation guide by setting the following configuration in your latest build.

``` toml
[Editor]
#...

IndentGuide = true
OptionsToUseGuideWidth = "shiftwidth"
```
