### ISSUE TITLE
Question: is it possible to move from filer to buffer without closing it?

### ISSUE THREAD

**Issue by lbiaggi** [akiyosi/goneovim#263]

**Comment by akiyosi** [comment]
Hi,
Try the following setting:

``` toml
[Sidebar]
Visible = true
```
