### ISSUE TITLE
Very slow when using split windows in v0.4.12

### ISSUE THREAD

**Issue by benallan** [akiyosi/goneovim#279]
When I try using the windows release build of v0.4.12, and I open two side by side splits in neovim, my editor becomes extremely slow. If I switch back to v0.4.11 the problem disappears (the speed is completely fine), so to me this looks like a regression in v0.4.12. 

My goneovim settings are quite close to default, and I have most of the fancy visual features (e.g. scroll bar) turned off, so I'm not sure what's causing it. I do use a lot of neovim plugins so I'll start investigating those, but it's strange that I had no problems on v0.4.11.

If you have any ideas about what might cause this or what I should check next I'd be very grateful. Thanks!

settings.toml:
```toml
[Editor]
FontFamily = "Hack NF"
FontSize = 10

ExtCmdline   = false
ExtPopupmenu = true
ExtTabline   = false

DisableImeInNormal = true

[Popupmenu]
 
[ScrollBar]

[Markdown]
CodeHlStyle = "solarized-light"

[SideBar]
```

OS: Microsoft Windows [Version 10.0.19042.1288]
Neovim: v0.5.1
Goneovim: v0.4.12
