### ISSUE TITLE
Cursor line shifts up when remote attached

### ISSUE THREAD

**Issue by shiena** [akiyosi/goneovim#353]
goneovim: v0.5.1-87-gaa788ad
neovim: v0.7.0
OS: Windows10

**~/.goneovim/settings.toml**

```toml
[Editor]
FontFamily = "UDEV Gothic 35JPDOC"
FontSize = 12
ExtCmdline   = true
ExtTabline   = true
Clipboard = true

Ginitvim = '''
nnoremap <Leader>mm :<C-u>GonvimMiniMap<CR>
nnoremap <Leader>ma :<C-u>GonvimMaximize(1)<CR>
nnoremap <Leader>mi :<C-u>GonvimMaximize(0)<CR>
nnoremap <Leader>wo :<C-u>GonvimFilerOpen<CR>
nnoremap <Leader>wn :<C-u>GonvimWorkspaceNew<CR>
'''


[Cursor]
SmoothMove = true
```

Steps to reproduce

1. run `nvim --listen localhost:11111 -u NONE`
2. run `goneovim --server localhost:11111`

![image](https://user-images.githubusercontent.com/1295639/166160367-4d00a491-d7ff-4fb6-8346-79a1251d0aff.png)
