### ISSUE TITLE
Titlebar on MacOS

### ISSUE THREAD

**Issue by PhrantiK** [akiyosi/goneovim#365]
Is there a way to turn off the titlebar and buttons in MacOS?

I've tried toggling the BorderlessWindow feature in the config but it doesn't seem to make a difference to the window. 

Currently running Monterey 12.4 and the yabai window manager with SIP turned off.

**Comment by akiyosi** [comment]
@PhrantiK 
Hi :D 
I have added a setting item to hide the title bar when in a borderless window.
Could you please try it?

https://github.com/akiyosi/goneovim/actions/runs/2643456839

To set it up, add the following setting to settings.toml

```toml
[Editor]
# ...
BorderlessWindow = true
HideTitlebar = true
# ...
```
