### ISSUE TITLE
Bold and normal characters have different width

### ISSUE THREAD

**Issue by acomagu** [akiyosi/goneovim#375]
Bold characters seem to be rendered wider than normal character. This causes overlapping characters.

![image](https://user-images.githubusercontent.com/1362750/175499494-0d391c3c-1d28-4a1e-bcc2-6fa3fd68c24b.png)

Only the `/` character is shifted.

![image](https://user-images.githubusercontent.com/1362750/175495319-4a7b6f27-4b7c-4f27-9cb7-26b64cb5c0fa.png)

Happens only when specifies font weight. `guifont=Source\ Code\ Pro` is not problematic, but `guifont=Source\ Code\ Pro\ Light` causes the problem.

`set guifont=Source\ Code\ Pro:h11:l` doesn't work(always Regular weight). Setting `FontFamily="Source Code Pro Light"` at settings.toml gets same result.

goneovim Nightly gb131248 Windows

My settings.toml:

```toml
[Editor]
ExtCmdline   = true
ExtPopupmenu = true
ExtTabline   = true
ExtMessages  = true
CachedDrawing = false
DrawWindowSeparator = true
DrawBorderForFloatWindow = true
[ScrollBar]
Visible = true
[MiniMap]
Disable = true
```

Thanks!!
