### ISSUE TITLE
ExtMessage exceeds from window

### ISSUE THREAD

**Issue by acomagu** [akiyosi/goneovim#377]
![image](https://user-images.githubusercontent.com/1362750/175817168-8955b577-b704-419e-9a11-9b3499791942.png)

Long ExtMessage exceeds from the window and some characters are hidden so can't be read. Line breaking position seems wrong.

Seems Hi-DPI setting is not a factor(reproduced even if pixel-by-pixel scale).

goneovim Nightly gb131248 Windows

settings.toml:

```toml
[Editor]
ExtCmdline   = true
ExtPopupmenu = true
ExtTabline   = true
ExtMessages  = true
CachedDrawing = false
DisableLigatures = true
DrawWindowSeparator = true
DrawBorderForFloatWindow = true
[ScrollBar]
Visible = true
[MiniMap]
Disable = true
```

Thank you :bow:
